---
# yaml-language-server: $schema=https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json
stages:
  - gate

include:
  - local: .gitlab-ci/workflows/gate-commit-check.yml
