---
- name: "merge_variables | Merge configuration for server"
  when:
    - k3s_mode == 'server'
  block:
    - name: "merge_variables | Merge server specific configuration"
      vars:
        _config_to_merge: "{{ k3s_server_configuration }}"
      ansible.builtin.set_fact:
        k3s_configuration: "{{
          k3s_configuration |
          combine(_config_to_merge, recursive=true)
          }}"

    - name: "merge_variables | Merge listeners configuration"
      vars:
        _config_to_merge: "{{ k3s_server_listeners_options }}"
      ansible.builtin.set_fact:
        k3s_configuration: "{{
          k3s_configuration |
          combine(_config_to_merge, recursive=true)
          }}"

    - name: "merge_variables | Merge datastore configuration"
      vars:
        _config_to_merge: "{{ k3s_server_datastore_options }}"
      ansible.builtin.set_fact:
        k3s_configuration: "{{
          k3s_configuration |
          combine(_config_to_merge, recursive=true)
          }}"

    - name: "merge_variables | Merge networking configuration"
      vars:
        _config_to_merge: "{{ k3s_server_networking_options }}"
      ansible.builtin.set_fact:
        k3s_configuration: "{{
          k3s_configuration |
          combine(_config_to_merge, recursive=true)
          }}"

    - name: "merge_variables | Merge components configuration"
      vars:
        _config_to_merge: "{{ k3s_server_components_options }}"
      ansible.builtin.set_fact:
        k3s_configuration: "{{
          k3s_configuration |
          combine(_config_to_merge, recursive=true)
          }}"

    - name: "merge_variables | Merge processes flags configuration"
      vars:
        _config_to_merge: "{{ k3s_server_processes_flags_options }}"
      ansible.builtin.set_fact:
        k3s_configuration: "{{
          k3s_configuration |
          combine(_config_to_merge, recursive=true)
          }}"

    - name: "merge_variables | Merge experimental configuration"
      vars:
        _config_to_merge: "{{ k3s_server_experimental_options }}"
      ansible.builtin.set_fact:
        k3s_configuration: "{{
          k3s_configuration |
          combine(_config_to_merge, recursive=true)
          }}"

- name: "merge_variables | Merge configuration for agent"
  when:
    - k3s_mode == 'agent'
  block:
    - name: "merge_variables | Merge agent specific configuration"
      vars:
        _config_to_merge: "{{ k3s_agent_configuration }}"
      ansible.builtin.set_fact:
        k3s_configuration: "{{
          k3s_configuration |
          combine(_config_to_merge | from_yaml, recursive=true)
          }}"

    - name: "merge_variables | Merge networking configuration"
      vars:
        _config_to_merge: "{{ k3s_agent_networking_options }}"
      ansible.builtin.set_fact:
        k3s_configuration: "{{
          k3s_configuration |
          combine(_config_to_merge | from_yaml, recursive=true)
          }}"

    - name: "merge_variables | Merge node configuration"
      vars:
        _config_to_merge: "{{ k3s_agent_node_options }}"
      ansible.builtin.set_fact:
        k3s_configuration: "{{
          k3s_configuration |
          combine(_config_to_merge | from_yaml, recursive=true)
          }}"

    - name: "merge_variables | Merge runtime configuration"
      vars:
        _config_to_merge: "{{ k3s_agent_runtime_options }}"
      ansible.builtin.set_fact:
        k3s_configuration: "{{
          k3s_configuration |
          combine(_config_to_merge | from_yaml, recursive=true)
          }}"

    - name: "merge_variables | Merge processes flags configuration"
      vars:
        _config_to_merge: "{{ k3s_agent_processes_flags_options }}"
      ansible.builtin.set_fact:
        k3s_configuration: "{{
          k3s_configuration |
          combine(_config_to_merge | from_yaml, recursive=true)
          }}"

    - name: "merge_variables | Merge experimental configuration"
      vars:
        _config_to_merge: "{{ k3s_agent_experimental_options }}"
      ansible.builtin.set_fact:
        k3s_configuration: "{{
          k3s_configuration |
          combine(_config_to_merge | from_yaml, recursive=true)
          }}"
