---
- name: "prerequisites | Create directory {{ k3s_config_dir }}"
  ansible.builtin.file:
    path: "{{ k3s_config_dir }}"
    state: directory
    owner: "{{ k3s_user }}"
    group: "{{ k3s_group }}"
    mode: "0755"

- name: "prerequisites | Create directory {{ k3s_data_dir }}"
  ansible.builtin.file:
    path: "{{ k3s_data_dir }}"
    state: directory
    owner: "{{ k3s_user }}"
    group: "{{ k3s_group }}"
    mode: "0755"
